### PR TITLE
Add GUI (Static Buttons)

### PR DESCRIPTION
**Pull request by ayush-seth**
1. Add all the required buttons using clean for loops.
2. Fix a missing bracket in Button class
3. Change the size of button to be a square
4. Bumped up the font size and changed some colors

### CODE REVIEW

**Comment by ayush-seth** [comment]
This is how it looks
image

**Comment by GideonBuckwalter** [comment]
Oh wow, this looks great! +1 +1 +1

What merge conflicts are you seeing?

**Comment by joseph-allen** [comment]
Apologies , we have three PR for the same thing so I already merged the first one I saw.
You may want to pull the master branch if you think any of these changes still apply?

[PR](https://github.com/joezcool02/OurCalculator/pull/42)

**Comment by joseph-allen** [comment]
@GideonBuckwalter I will see if i can resolve the conflicts here, it is an issue on my part that 3 people have solved the same issue at once :)

**Comment by joseph-allen** [comment]
nah it's a mess. @MasterYushi I like your GUI and I like @GideonBuckwalter and @wootai s ways of drawing the buttons, could you maybe have a look at putting your stuff into a new PR off master?

**Comment by ayush-seth** [comment]
You can decline this one, and I can make a new PR with the same things, but with the updated, already added buttons and click functionality, these buttons here are just static and nothing happens on being pressed.

**Comment by ayush-seth** [comment]
I think you misinterpreted, I drew all the buttons using two for loops, and the original one I saw had a bunch of statements, each for one of the buttons

**Comment by joseph-allen** [comment]
yes perhaps. I just read three PRs my mind is a little boggled :) I trust you MasterYushi!

**Comment by GideonBuckwalter** [comment]
NO NO NO @joezcool02  go with @MasterYushi 's pull request! It's a lot better than mine! Any way to revert the merge?

**Comment by ayush-seth** [comment]
I will do a new one, after pulling master into my repo

**Comment by joseph-allen** [comment]
@MasterYushi @GideonBuckwalter , I have sorted it now :) should be okay?

**Comment by ayush-seth** [comment]
@joezcool02 Looks good! Thanks, Let me know if there is something else I can help with!

**Comment by GideonBuckwalter** [comment]
Great!

**Comment by joseph-allen** [comment]
this is all good now and works on my machine as well so I guess next big thing is getting pushed numbers to show up at the top and then we can start adding operators and the clear function?

**Pull request merged**
