### PR TITLE
Eval

### PR DESCRIPTION
**Pull request by FreedomGrenade**

### CODE REVIEW

**Comment by FreedomGrenade** [comment]
What's with those first 4 commits.

**Comment by ayush-seth** [comment]
You commited them so you would know

**Comment by FreedomGrenade** [comment]
> You commited them so you would know  

Well no, I'm using this project as an opportunity to learn git.  

The merge I understand, but do they always have to be there?
But the OC-1 was already done.

**Comment by FreedomGrenade** [comment]
Oh, also this:  

`gui.expression.append((answer instanceof Double)?((Double)answer).floatValue():answer);`

to tidy division output.

**Comment by joseph-allen** [comment]
Git will automatically commit when you try to deal with merges, thats what those few are :)

**Comment by ayush-seth** [comment]
I don't see why these merges were required or why you merged the eval branch of this into the eval branch of your fork, when you fork a repo, you get all the branches with it.

image

my guess is you created an `eval` branch on your fork and then merged our `eval` to your `eval`. You don't need to do that. Either delete these commits and commit them again, or you can make a new fork, or just force pull again into your fork. Then you will have a `eval` branch you can commit to and then file a new  PR.

Of course, we could just fix this one and merge it in but redoing this properly will be a good lesson for you on how git works!

**Comment by ayush-seth** [comment]
Also, just a common practice with commit messages is you type them like `Add some calculator input cleansing` instead of `Added some calculator input cleansing` and similar. However, it is just a convention and does not need to be followed strictly, but is recommended.

**Comment by joseph-allen** [comment]
when we merge it we squash it all into one commit anyway so it won't matter and shouldn't affect our master branch anyway since we don't care what branch we merge in :)

**Comment by ayush-seth** [comment]
@joezcool02 It would still be a good lesson for him and will keep our commit history clean

**Pull request closed without merging**
