### PR TITLE
button lettering changed to blue

### PR DESCRIPTION
**Pull request by akathewb**
Didn't realize it pull all the way back to the main project. My bad.
Thanks for starting this collaboration project. I just watched the coding train git and git hub videos.... and read the beginners guide you all posted.

### CODE REVIEW

**Review by GideonBuckwalter — CHANGES_REQUESTED** [review]
Thanks for contributing! Committing to `master` is fine when your changes are unrelated to what's happening over in `eval`.

I'm all for sprucing up the color scheme, but I think we should go for something a little more subtile and/or cohesive. Would you be interested in doing some experimentation (here are some resource: [paletton.com](http://paletton.com), [Website Color Schemes](https://designschool.canva.com/blog/website-color-schemes/)) and then posting pictures of any interface redesign ideas you come up with?

**Comment by JornPrengerFormeel** [comment]
Cookies.co

**Comment by JornPrengerFormeel** [comment]
Coolors.co*

**Comment by joseph-allen** [comment]
nice one @jorn600 

This PR is an interesting example, most things like this need an issue, we had had ten people changing colors all the time it could become very confusing very quickly!

**Pull request closed without merging**
