### PR TITLE
Add additional calculator input cleansing

### PR DESCRIPTION
**Pull request by FreedomGrenade**
Well this looks right as far as I can tell.

### CODE REVIEW

**Comment by ayush-seth** [comment]
What does this do? 
`if (input.matches("(.*)[*/][*/](.*)")) throw new ScriptException(new UnsupportedOperationException());`

**Comment by FreedomGrenade** [comment]
if input (expression string) matches the regex of  `** */ /* //`, throw ScriptExcepetion( Unspupported).

Since the script engine is js, it's accepting comments which a pure math parser would probably consider errors.

I figured it should throw the same error the scriptEngine does.  I didn't check what other Exception the scriptEngines ScriptException wrapped and just used UnsupportedOperationException.  

I know the ** is redundant as it would fail in the scriptEngine, but I guess it saves from trying an already invalid expression.

**Comment by ayush-seth** [comment]
I get your point but just throwing the error out there will make the calculator crash anyways, instead of throwing it, put it in a try catch and just display "Invalid input" like it is done in the code

**Review by GideonBuckwalter — APPROVED** [review]
Looks good to me! Thanks for explaining the confusing regex.

**Comment by FreedomGrenade** [comment]
@MasterYushi eh, I was just trying to avoid duplicate code.   Since the error is only thrown in the existing try catch it's handled already, and the ouput would be invalid output.

**Comment by ayush-seth** [comment]
I have a better idea, to deal with // being valid, when you press = it just returns null, whatever you type it will return null so just check if output == null, display invalid output

**Comment by FreedomGrenade** [comment]
Sounds good.

**Comment by FreedomGrenade** [comment]
@MasterYushi   
Do you mean something like this?  
```
  void evaluate() {
    String express = gui.expression.toString();
    
    // prevalidate expression
    // handles js comments being valid, also ** which would fail anyway
    if (express.matches("(.*)[*/][*/](.*)")) {
      gui.expression = new StringBuilder("Invalid Input");
      return;
    }
    // modify -- to +
    express = express.replaceAll("-{2}","+");
    // sqush ++... to +
    express = express.replaceAll("\\+{2,}","+");
    
    try {
      Object answer = engine.eval(express);
      gui.expression.delete(0, gui.expression.length());
      gui.expression.append(answer);
    } 
    catch(ScriptException e) {
      gui.expression = new StringBuilder("Invalid Input");
    }
  }
```

Also, I wonder if the calculator should just have some options like setInvalid(), setAnswer() ?

**Pull request closed without merging**
