### PR TITLE
Add GUI class and clean main sketch

### PR DESCRIPTION
**Pull request by ayush-seth**
I think we should merge this now, no point in keeping it different since it is working now.

### CODE REVIEW

**Comment by joseph-allen** [comment]
agreed, though it is considered bad practice to merge your own commits :) should  have at least one review on everything

**Comment by ayush-seth** [comment]
I didn't get you here. Can you elaborate a bit? 

Anyways i had to merge this because the new evaluation code was based on the new clean main sketch setup which was in gui branch and if a branched off without merging it would have created unnecessary clutter and conflicts

**Comment by joseph-allen** [comment]
@MasterYushi , can we make sure we keep things tied with an issue number? It is now very difficult to tell which issues are resolved and can be closed.

**Comment by joseph-allen** [comment]
generally we say that somebody else has to acknowledge code looks good before it is merged in, otherwise you or me could make any change we want and merge it in without anybody elses input.

**Comment by ayush-seth** [comment]
Instead of giving them numbers we could just use their default numbers, and add that number in the commit message saying "resolves #--" and then test it out and close the issue

**Comment by joseph-allen** [comment]
yeah that works too, as long as there is something I don't mind.

at work we have something that auto-increments and gives a ticket number based on the project so I am just used to it, but that works fine! As long as there is something

**Pull request merged**
