### PR TITLE
Issue 13: Added Display 

### PR DESCRIPTION
**Pull request by Wootai**
Resolves issue 13 and adds display to calculator.

### CODE REVIEW

**Comment by ayush-seth** [comment]
You can pull my commit from [my fork](https://github.com/MasterYushi/OurCalculator) which adds button functionality, and build on that if you want to change something and then open a pull request here, I think you just implemented what I already did. Or you can wait for my changes to be merged and then update your fork.

**Comment by ayush-seth** [comment]
Also, some constructive feedback if it is welcomed:

You don't need to loop through all the buttons every time through `draw`, you just need to check which one is clicked on when mouse is clicked so all that can be moved from `draw` to `mousePressed`, which is how it's implemented in my [PR](https://github.com/joezcool02/OurCalculator/pull/47)

**Comment by joseph-allen** [comment]
your commits seem to be doing some really weird stuff @MasterYushi, they seem to be removing and adding almost every single line? It makes it hard to tell what has been added

**Comment by ayush-seth** [comment]
@joezcool02 I know that's been happening, the same applies to this PR, I don't know what's causing that, I am definitely not deleting the whole code and typing it again!

**Comment by joseph-allen** [comment]
@MasterYushi can you try to fix the conflict here? Your commits seem to add almost every single line as a change so I cannot actually see what you have changed in the git editor :(

**Comment by joseph-allen** [comment]
or branch off master now and do it again as i have merged in the other :S

**Comment by ayush-seth** [comment]
@joezcool02 Only owners can see that, although if you are wondering what I added, here's a gif 

ourcalculator

**Comment by ayush-seth** [comment]
@joezcool02 Okay I seem to have figured out what's happening with git diff, I bet you are on mac which uses LF to terminate lines, I am on windows which uses CRLF to terminate lines, which makes git diff think that each line is changed. We'll have to decide on one of them

**Comment by ayush-seth** [comment]
@joezcool02 this is what you will need to add to this repo to fix it https://help.github.com/articles/dealing-with-line-endings/#per-repository-settings

**Comment by joseph-allen** [comment]
fair enough. What would you like to do about this branch then? you can resolve the conflicts yourself using Git and it will let me merge

**Comment by ayush-seth** [comment]
@joezcool02 I cannot see/resolve the merge conflicts, only the submitter and you can do that

**Comment by joseph-allen** [comment]
yep, I keep forgetting this isn't your branch!

**Comment by ayush-seth** [comment]
I'll see if I can switch to lf from crlf for future commits to make it easy for you, till then I'll be working on evaluating the expression and submit a PR as soon as I get it done, perhaps you can open a new issue for this and assign it to me?

**Comment by ayush-seth** [comment]
I think this needs to be closed and resubmitted if you think these changes still apply, I can't resolve the conflicts here because git shows the whole file as a conflict probably because of the line ending issues, so it is probably a good idea to resubmit this PR after pulling from this repo so we all have consistent line endings.

I'll be closing this one now.

**Comment by joseph-allen** [comment]
@MasterYushi yep, if @Wootai pulls down master and then pushes the same commit it should sort it

**Pull request closed without merging**
