### PR TITLE
Buttons Flash then Fade Back when Clicked

### PR DESCRIPTION
**Pull request by GideonBuckwalter**
Sorry, I really screwed up the commit history this time. It looks like I changed EVERYTHING, but it actually only alters about 20 lines.

Adds two new functions to `Button`: pulse and updateColors
Adds three new instance attributes: bgColor, textColor, and bgBrightness
Adds two new `final color` class variables: BRIGHT and DARK

### CODE REVIEW

**Comment by ayush-seth** [comment]
You can save your code somewhere else, then hard reset your HEAD to the last commit on this repo,  then you can commit all the new changes you want and file another PR to fixed the messed up commits

**Comment by ayush-seth** [comment]
@GideonBuckwalter I would recommend you to update your forked repo with the current state of this repo, your forked repo is 10 commits behind this one, and 8 commits ahead, which I suppose are the 8 commits in this PR, before submitting a new PR, you should make sure that your fork is even with the original repo:

This is how your repo looks:

image

This is how my repo looks:

image

Your repo should look like this too, except it should not be 1 commit ahead, that is because I added the gitattributes file. Ideally, your repo should say just *8 commits ahead*

**Comment by joseph-allen** [comment]
yes, it is good practice to "git pull" everytime you sit down to do some work :)

**Comment by GideonBuckwalter** [comment]
Ok, thanks for the help. I'll see what I can do.

**Pull request closed without merging**
