### PR TITLE
OC-5 Button class

### PR DESCRIPTION
**Pull request by Floempie**
Making a generic button class

### CODE REVIEW

**Comment by joseph-allen** [comment]
a great start, I am going to use this as an opportunity to teach reviewing

**Comment by joseph-allen** [comment]
@Floempie  , @jorn600. If you click on "files changed at the top you should be able to review the code by clicking on lines you agree/disagree with to ask questions about implementation where you do or do not understand.

I will wait for a review from both of you before merging :)

**Comment by joseph-allen** [comment]
apologies, just jorn to do a review :)

**Comment by joseph-allen** [comment]
@jorn600 there is an official review process you can you do in Github [Check this out](https://help.github.com/articles/reviewing-proposed-changes-in-a-pull-request/)

**Review by GideonBuckwalter — APPROVED** [review]
Looks good.

**Pull request merged**
