### PR TITLE
OC-1 Added add function

### PR DESCRIPTION
**Pull request by FreedomGrenade**

### CODE REVIEW

**Comment by jorn600** [comment]
you need to provide a description, if added adding oc-1, if you added multiplying oc-2

**Comment by FreedomGrenade** [comment]
I didn't realize this was tasked to jorn, whoops.

**Review by GideonBuckwalter — APPROVED** [review]
I like it.

**Comment by joseph-allen** [comment]
I like it too, as a learning exercise I will leave it until Jorn finishes his as well :)

**Comment by JornPrengerFormeel** [comment]
i now know how to do this, merge this request and ill delete my pr

**Pull request merged**
